apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: <repo-url>
    targetRevision: HEAD
    path: <path-to-yaml-files>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

