apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-app-pipeline
spec:
  tasks:
  - name: build-and-push
    taskRef:
      name: build-docker-image
    params:
    - name: IMAGE
      value: your-docker-image-name

